Vagrant::Config.run do |config|
  config.vm.box = "civix"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.host_name = "vagrant"
  config.vm.forward_port 80, 8080
  config.vm.network :hostonly, "192.168.100.100"
end